### ISSUE TITLE
OfflineImport

### ISSUE THREAD

**Issue by jungla-team** [oe-alliance/XMLTV-Import#52]
With the **enigma2-plugin-extensions-epgimport - 1.0+git228+c171b44-r0** version the OfflineImport script works fine:

```
/usr/bin/python /usr/lib/enigma2/python/Plugins/Extensions/EPGImport/OfflineImport.pyo /etc/epgimport/rytec_koala7.xml

[EPGImport] oudeis patch not detected, using epg.dat instead.
[EPGImport] using C module, yay
[EPGImport] nextImport, source= Koala 7 dias XMLTV
[EPGImport] Downloading: http://tropical.jungle-team.online/epg/koala7.xml.gz to local path: /tmp/epgimport.gz
[EPGImport] No IPv6, using IPv4 directly: http://tropical.jungle-team.online/epg/koala7.xml.gz
[EPGImport] afterDownload /tmp/epgimport.gz
[EPGImport] unlink /tmp/epgimport.gz
[EPGImport] Downloading: http://tropical.jungle-team.online/epg/koala_epg.channels.xml.gz to local path: /tmp/epgimport.gz
[EPGImport] No IPv6, using IPv4 directly: http://tropical.jungle-team.online/epg/koala_epg.channels.xml.gz
[EPGImport] afterChannelDownload /tmp/epgimport.gz
[EPGImport] Using twisted thread
[EPGImport] Parsing channels from 'http://tropical.jungle-team.online/epg/koala_epg.channels.xml.gz'
[XMLTVConverter] Enumerating event information
Unknown channel:  m. laliga 10
Unknown channel:  m. deportes1
Unknown channel:  m.lcampeones hd
Unknown channel:  canal sur hd
Unknown channel:  cnc world
Unknown channel:  discovery max
Unknown channel:  la 2 hd
[EPGImport] ### importEvents exception: ubyte format requires 0 <= number <= 255
[EPGImport] ### importEvents exception: ubyte format requires 0 <= number <= 255
[EPGImport] ### importEvents exception: ubyte format requires 0 <= number <= 255
[EPGImport] ### importEvents exception: ubyte format requires 0 <= number <= 255
Unknown channel:  el toro tv
Unknown channel:  intereconomía
Unknown channel:  mtv hits
Unknown channel:  mtv music
Unknown channel:  sol música
Unknown channel:  dmax
[EPGImport] ### thread is ready ### Events: 40404
[EPGImport] imported 40404 events
[EPGImport] no Oudeis patch, load(/media/hdd/epg_new.dat) required
Done, data is in /media/hdd/epg_new.dat
[EPGImport] #### Finished ####
```
 but with then new version of the plugin **enigma2-plugin-extensions-epgimport - 1.0+git230+a3af774-r0** doesn't work:

/usr/bin/python /usr/lib/enigma2/python/Plugins/Extensions/EPGImport/OfflineImport.pyo /etc/epgimport/rytec_koala7.xml
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGImport/OfflineImport.py", line 13, in <module>
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGImport/EPGImport.py", line 12, in <module>
ValueError: Attempted relative import in non-package

**Comment by thawtes** [comment]
OfflineImport not working since last update
this update https://github.com/oe-alliance/XMLTV-Import/commit/a848f6ea018f43a90b6924f5240e4c632992e4cf

@atvcaptain , @kiddac

**Comment by Huevos** [comment]
@jungla-team please see this commit... and please give feedback.
https://github.com/oe-alliance/XMLTV-Import/commit/5714422eebdb3ff4a89bc0294672dc25172ae141
